-- Admin phase schema updates
ALTER TABLE users ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS agent_verified BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE videos ADD COLUMN IF NOT EXISTS hidden BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS flagged BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE stadiums ADD COLUMN IF NOT EXISTS pitch_count INTEGER NOT NULL DEFAULT 1;
ALTER TABLE stadiums ADD COLUMN IF NOT EXISTS open_time TIME;
ALTER TABLE stadiums ADD COLUMN IF NOT EXISTS close_time TIME;
ALTER TABLE stadiums ADD COLUMN IF NOT EXISTS grass_type VARCHAR(255);
ALTER TABLE stadiums ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE stadiums ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

CREATE TABLE IF NOT EXISTS stadium_pitch_types (
    stadium_id BIGINT NOT NULL REFERENCES stadiums(id),
    pitch_type VARCHAR(255) NOT NULL
);

ALTER TABLE lessons ADD COLUMN IF NOT EXISTS media_url VARCHAR(2048);
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS media_type VARCHAR(255);
